[tool.pytest.ini_options]
# !!!!!!!!!!Esto resuelve el problema de la ruta de importaci贸n de tu c贸digo fuente
pythonpath = "src"

# Especifica d贸nde buscar los tests si no quieres usar la convenci贸n
testpaths = ["src", "tests"]